DATA:
    ROOT: './data/TCGA-lung-patch_report/LUAD-patch'
    TRAIN_FILE: './data/TCGA-lung-patch_report/LUDA_data_train_reid.csv'
    VAL_FILE: './data/TCGA-lung-patch_report/LUDA_data_val_reid.csv'
    LABEL_LIST_TRAIN: './data/TCGA-lung-patch_report/LUAD_labels_train_reid.csv'
    LABEL_LIST_VAL: './data/TCGA-lung-patch_report/LUAD_labels_val_reid.csv'
    DATASET: kinetics400
    NUM_FRAMES_PERCENT: 0.25
    NUM_FRAMES: 512

    NUM_CLASSES: 16
MODEL:
    ARCH: ViT-B/16
    CONTEXT_LENGTH: 308 # max 267
    FIX_TEXT: False
    FIX_IMAGE: False
#    PRETRAINED: './data/k400_16_16.pth'

    ATTN_BATCH: 16
    VIT_VISION_LAYERS: 4 # 12
    VIT_TEXT_LAYERS: 4 # 12
TRAIN:
    BATCH_SIZE: 8
    ACCUMULATION_STEPS: 32
    EPOCHS: 150
#    OPT_LEVEL: 'O0'
#    LR: 1.6e-3
AUG:
    MIXUP: 0.0
#TEST:
#    ONLY_TEST: True
